services:
  - type: web
    name: flask-telegram-redirect-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: WEBHOOK_URL
        sync: false
